version: '3'
services:
  php:
    build:
      context: ./
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./code:/var/www/html/
      - ./docker/php/settings/php.ini:/usr/local/etc/php/php.ini
    ports:
      - 80:80
    links:
      - mysql:mysql
  mysql:
    build:
      context: ./
      dockerfile: ./docker/mysql/Dockerfile
    volumes:
      - ./mysql/mysql:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password1
  phpmyadmin: 
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=password1
    links:
      - mysql
    ports:
      - 4000:80
    volumes:
      - ./phpmyadmin/sessions/:/sessions

