version: '3'
services:
  php:
    build:
      context: ./
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./code:/var/www/html/
      - ./docker/php/settings/php.ini:/usr/local/etc/php/php.ini
    ports:
      - 80:80
    links:
      - mysql:mysql
  mysql:
    image: mysql:latest
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - 13306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_DATABASE=cms
      - MYSQL_USER=usr1
      - MYSQL_PASSWORD=pass
  phpmyadmin: 
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=usr1
      - PMA_PASSWORD=pass
    links:
      - mysql
    ports:
      - 4000:80
    volumes:
      - ./phpmyadmin/sessions/:/sessions

